spring.application.name=backend

app.jwt.secret=change-this-secret-key-before-production

spring.datasource.url=jdbc:postgresql://localhost:5432/energysimulatordb
spring.datasource.username=SimulatorUser
spring.datasource.password=SimulatorUserPassword123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.http.converters.preferred-json-mapper=gson

logging.level.org.springframework.web=debug
logging.level.org.springframework.http.converter.json=debug
debug=true

server.error.whitelabel.enabled=false
