services:
  # --- Base de datos PostgreSQL ---
  db:
    image: postgres:18-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=energysimulatordb
      - POSTGRES_USER=SimulatorUser
      - POSTGRES_PASSWORD=SimulatorUserPassword123
    volumes:
      - ./database:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U SimulatorUser -d energysimulatordb"]
      interval: 5s
      timeout: 5s

      retries: 5

  #--- Backend Spring Boot ---
  backend:
    image: eclipse-temurin:25-jre-alpine
    container_name: backend
    restart: unless-stopped
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    volumes:
      - ./backend/backend-0.0.1-SNAPSHOT.jar:/app/app.jar:ro
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/energysimulatordb
      - SPRING_DATASOURCE_USERNAME=SimulatorUser
      - SPRING_DATASOURCE_PASSWORD=SimulatorUserPassword123
      - SERVER_PORT=8081
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  #--- Inicializador de datos (usa backend/InsertDemoData.sql) ---
  db-init:
    image: postgres:18-alpine
    container_name: db-init
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - PGPASSWORD=SimulatorUserPassword123
    volumes:
      - ./backend/InsertDemoData.sql:/init.sql:ro
    entrypoint: >
      sh -c "
        echo 'Esperando 5 segundos extra para asegurar que las tablas estén creadas...';
        sleep 5;
        echo 'Insertando datos de prueba...';
        psql -h db -U SimulatorUser -d energysimulatordb -f /init.sql;
        echo 'Datos insertados correctamente.';
      "

  # --- Frontend Nginx ---
  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
